// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhuBRy6FtlMPfZ1rhy336XyjnqcOQWp0',
    appId: '1:77085531765:web:2c0ceb1adc1ffeea02223c',
    messagingSenderId: '77085531765',
    projectId: 'fullstack-flutter-project',
    authDomain: 'fullstack-flutter-project.firebaseapp.com',
    storageBucket: 'fullstack-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVipuoR-YVH8Pi9sMqCY1wZ-_n3eZVvhg',
    appId: '1:77085531765:android:d1e8c6b6654862aa02223c',
    messagingSenderId: '77085531765',
    projectId: 'fullstack-flutter-project',
    storageBucket: 'fullstack-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWVRysD0MTOnm_IHJRFNWQbw7yD9_2Vqw',
    appId: '1:77085531765:ios:89f431765d50503102223c',
    messagingSenderId: '77085531765',
    projectId: 'fullstack-flutter-project',
    storageBucket: 'fullstack-flutter-project.appspot.com',
    iosClientId: '77085531765-a22tu0ue1hrr53ubo88uc6u6k6q66q1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWVRysD0MTOnm_IHJRFNWQbw7yD9_2Vqw',
    appId: '1:77085531765:ios:89f431765d50503102223c',
    messagingSenderId: '77085531765',
    projectId: 'fullstack-flutter-project',
    storageBucket: 'fullstack-flutter-project.appspot.com',
    iosClientId: '77085531765-a22tu0ue1hrr53ubo88uc6u6k6q66q1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
